-- Sprint 1's data file, moved into the database. Run once, in the Supabase
-- SQL Editor. Kept in the repo as the record of what was seeded; the owner
-- uuid is an account id, not a secret, and the keys are not in here.
insert into entries (
  owner, created_at, slug, title, khmer_term, category, description, flavor_profile, photo, photo_note, how_made, what_used_for, how_recipes_vary, source_credit, status
) values
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T12:00:00.000Z',
   'prahok',
   'Prahok',
   'ប្រហុក',
   'Fermented Fish Paste',
   'Salted, dried, and packed into clay jars to ferment for weeks — sometimes years — prahok turns freshwater catches from the Tonlé Sap (snakehead, featherback, riel) into an intensely pungent, salty paste. It''s the deep, funky note underneath samlor korko, amok, and prahok ktis — the flavor Khmer cooking is built on.',
   array['salty', 'pungent', 'savory', 'fermented']::text[],
   '/images/prahok.jpg',
   'A clay jar of dark, packed prahok paste with visible fish texture, next to a small dish of the paste served with fresh vegetables.',
   'Freshwater fish from the Tonlé Sap — snakehead, featherback, riel — are salted, dried, and packed into clay jars to ferment for weeks, sometimes years. The salt draws out moisture while natural enzymes break down the fish into a concentrated, intensely savory paste.',
   'Prahok is the deep, funky note underneath samlor korko, amok, and prahok ktis — the flavor Khmer cooking is built on. A pinch dissolves into soups, a spoonful thickens dips, and a smear on rice is a meal on its own.',
   'Some families ferment longer for a more pungent paste; others blend different ratios of fish species. A jar from Battambang can taste noticeably different from one made in Phnom Penh — each carries the signature of the kitchen that made it.',
   'grantourismotravels.com, figaroshakes.com, morethantemples.com',
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:59:00.000Z',
   'kroeung',
   'Kroeung',
   'គ្រឿង',
   'Herb & Spice Paste',
   'Pounded by hand in a stone mortar until lemongrass, galangal, turmeric, garlic, shallots, and kaffir lime dissolve into one fragrant paste, kroeung is the citrusy, earthy backbone of Khmer cuisine. Individual and royal blends, in yellow or red, shift the character of dish after dish.',
   array['aromatic', 'citrusy', 'earthy', 'herbal']::text[],
   '/images/kroeung.webp',
   'A stone mortar and pestle filled with freshly pounded green-yellow kroeung paste, with whole lemongrass, turmeric root, and kaffir lime leaves beside it.',
   'Lemongrass, galangal, turmeric, garlic, shallots, and kaffir lime are pounded by hand in a stone mortar until they dissolve into one fragrant paste. The pounding releases essential oils that no blender can replicate.',
   'Kroeung is the citrusy, earthy backbone of Khmer cuisine — the foundation of soups, curries, and stir-fries. It''s the first thing that hits the pan and the last thing you taste.',
   'Individual and royal blends come in yellow or red, shifting the character of dish after dish. Some families add more turmeric for colour, others more lemongrass for aroma. A royal kroeung might include kaffir lime peel and extra galangal.',
   'en.wikipedia.org/wiki/Kroeung, chefnak.com',
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:58:00.000Z',
   'tnot-skor',
   'Tnot Skor',
   'ស្ករត្នោត',
   'Palm Sugar',
   'Tapped from the sap of the Palmyra palm and slow-cooked down into granules, paste, block, or syrup, tnot skor (palm sugar) carries a deep, smoky caramel sweetness found nowhere else. Kampong Speu, its EU-recognized heartland, still divides the work by tradition: men climb the palms for sap, women cook it into sugar.',
   array['sweet', 'smoky', 'caramel', 'deep']::text[],
   '/images/tnot-skor.jpg',
   'Round blocks of golden-brown palm sugar stacked on a banana leaf, with a climber''s bamboo ladder against a palmyra palm trunk in the background.',
   'Sap is tapped from the inflorescence of the Palmyra palm and slow-cooked in wide woks until it reduces into granules, paste, blocks, or syrup. The longer it cooks, the darker and deeper the flavour becomes.',
   'Tnot skor carries a deep, smoky caramel sweetness used in desserts, sauces, marinades, and beverages — it''s the sweetener behind palm sugar lattes, caramel glazes, and traditional Khmer sweets.',
   'Kampong Speu, its EU-recognized heartland, still divides the work by tradition: men climb the palms for sap, women cook it into sugar. Cooking time and temperature vary by family, changing the sugar''s colour from golden blonde to deep espresso brown.',
   'fondazioneslowfood.com, tasteatlas.com, cambodianess.com',
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:57:00.000Z',
   'trey-ngeat',
   'Trey Ngeat',
   'ត្រីងៀត',
   'Dried & Cured Fish',
   'Trey ngeat is a traditional Cambodian dried fish — most commonly made from snakehead fish (trey ros), though any freshwater fish can be used. It''s cured with salt and sometimes sugar, chili, or a chicken soup base, then sun-dried until it develops a sweet-and-salty, smoky flavour.',
   array['sweet', 'salty', 'smoky', 'chewy']::text[],
   '/images/trey-ngeat.webp',
   'A woven tray of sun-dried trey ngeat — whole fish splayed open, glistening with salt crystals under the afternoon sun.',
   'Fresh fish — most commonly snakehead (trey ros) — are cleaned, split open, and rubbed with salt. Some families add sugar, chili, or a chicken soup base to the cure. The fish are then laid out under the sun for one to three days, depending on the weather, until they turn golden-brown and develop a smoky-sweet aroma.',
   'Trey ngeat is typically fried until crispy and served as a side dish with rice, fresh vegetables, and dipping sauce. It''s also crumbled over salads, stir-fried into noodles, or eaten as a snack — the salty-sweet crunch carries any dish it touches.',
   'The cure varies widely: some families keep it simple with just salt; others add garlic, palm sugar, or a commercial chicken soup powder for extra depth. The fish species changes too — snakehead is traditional, but catfish, mackerel, or even small river fish are used depending on what''s caught that season.',
   null,
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:56:00.000Z',
   'phaok',
   'Phaok',
   'ផ្អក',
   'Fermented Fish or Meat Paste',
   'Chopped fish or meat mixed with salt, sugar, yeast, and rice, then sealed airtight to ferment, phaok turns sour and savory over days — the base for ផ្អកចំហុយ (steamed phaok) and ផ្អកចិញ្ច្រាំ (fermented vegetable paste).',
   array['sour', 'savory', 'salty', 'fermented']::text[],
   '/images/phaok.jpg',
   'A glass jar of chopped, fermented phaok with visible rice grains, next to a steamed phaok dish served in a banana-leaf bowl.',
   'Chopped fish or meat is mixed with salt, sugar, yeast, and rice, then sealed airtight to ferment. The rice feeds the fermentation while the yeast and salt control spoilage, producing a sour-savory paste over days.',
   'Phaok is the base for ផ្អកចំហុយ (steamed phaok) and ផ្អកចិញ្ច្រាំ (fermented vegetable paste). It can be steamed as a side dish, stirred into soups, or used as a flavouring for stir-fried vegetables.',
   'Recipes vary by family: some use fish, others use pork or chicken. The fermentation time adjusts the sourness, and the choice of rice — sticky or regular — changes the texture from coarse to silky.',
   'My grandmother',
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:55:00.000Z',
   'sach-ko-ngeat',
   'Sach Ko Ngeat',
   'សាច់គោងៀត',
   'Dried & Cured Beef',
   'Lean beef is cut into long strips, rubbed with salt, sugar, garlic, and often a splash of fish sauce, then sun-dried until it turns dark, firm, and glossy. Chewy and savory-sweet, sach ko ngeat keeps for weeks without refrigeration — a snack, a side, and a way of carrying meat through the season.',
   array['savory', 'sweet', 'salty', 'chewy']::text[],
   '/images/sach-ko-ngeat.jpg',
   'Long strips of dark, sun-dried sach ko ngeat stacked on a woven bamboo tray, their surface glossy with cure.',
   'Lean beef — usually top round or sirloin — is trimmed of sinew, then cut into long strips along the grain. The strips are rubbed with salt, palm sugar, garlic, and often black pepper, and left to cure for a few hours or overnight so the seasoning draws into the meat. They are then laid on bamboo trays or hung on racks and sun-dried for one to three days, turned and pressed so they dry evenly and no moisture stays trapped inside. Once the strips are dark, firm, and glossy, they are rested for a day, then stored in a covered jar or in the refrigerator. Before eating they are grilled or fried until the edges crisp and the outside caramelises.',
   'Sach ko ngeat is most often grilled or fried and eaten with rice as a side dish, or torn into strips as a snack with beer. It is crumbled over rice porridge (borbor) and over plain rice, used as a filling for sandwiches and baguette-style rolls, and pounded with chili and lime into a chewy, savory relish. Because it needs no refrigeration, it is also classic travel food — wrapped in paper or banana leaf for long journeys.',
   'Every household cures it a little differently: some keep it to salt and sugar, others add garlic, galangal, black pepper, or a spoonful of honey, so the sweet-to-savory balance shifts from kitchen to kitchen. The cut matters too — thin strips dry fast and turn brittle, while thick pieces stay dense and chewy. Drying time depends on the weather and on how firm the cook wants the finished meat, and many families now dry it partway in the sun and finish it in the refrigerator. Texture is a point of pride: some like it leathery enough to chew for a while, others soft enough to tear by hand.',
   null,
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:54:00.000Z',
   'chaipov',
   'Chaipov',
   'ឆៃប៉ូវ',
   'Preserved Radish',
   'White radish is salted, pressed, and dried, then cured in a sweet-savory syrup until the strips turn amber and chewy. Crunchy, concentrated, and salty-sweet, chaipov is a small handful of flavor that Khmer kitchens keep on hand for omelettes, stir-fries, and rice porridge.',
   array['sweet', 'salty', 'crunchy', 'concentrated']::text[],
   '/images/chaipov.jpg',
   'Folded strips of golden-brown preserved radish piled on a small scalloped plate.',
   'Fresh white radish is washed, trimmed, and cut into thick strips, then heavily salted and left to draw out its water for a day or more. The salted radish is weighted down and pressed to squeeze out the remaining liquid, then spread out to dry in the sun until it is limp but still pliable. Many families then cure the dried strips in a sweet-savory brine of sugar, salt, and sometimes soy or fish sauce, letting them soak for several days until they take on an amber colour and a chewy bite. Packed tightly into jars, chaipov keeps for months; before use it is rinsed, sometimes soaked to soften, and chopped. Salt does the preserving first, and the sweet cure comes after to concentrate and round off the edge.',
   'Chopped fine, chaipov is stirred into egg omelettes and steamed egg dishes for a salty-sweet bite. It is fried with garlic as a side dish, added to stir-fried vegetables, pork, and noodles, and spooned over rice porridge (borbor) or plain rice. It also goes into savory-sweet braises and is set out as a condiment beside grilled meats.',
   'The balance of sugar to salt is the biggest variable — some families make a distinctly sweet, syrupy chaipov, others a saltier, drier one. The cut differs as well: fine shreds dry quickly and stay crisp, while thick strips stay meatier and chewier. Drying time is set by the weather and by how firm the cook wants the final texture, and some households skip the sweet cure entirely and simply salt and sun-dry the radish. Market stall to market stall, the same range shows up, so no two jars taste quite alike.',
   null,
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:53:00.000Z',
   'spey-jruk',
   'Spey Jruk',
   'ស្ពៃជ្រក់',
   'Fermented Mustard Greens',
   'Mustard greens are salted, packed tight, and left to ferment until they turn sour, crisp, and olive-green. Spey jruk is the Khmer pickle — a tangy, salty foil for rich grilled meats and heavy soups, made in jars that sit in the corner of the kitchen for weeks.',
   array['sour', 'salty', 'crisp', 'fermented']::text[],
   '/images/spey-jruk.jpg',
   'A wooden bowl of chopped, fermented mustard greens with fresh red chilies and lime wedges beside it.',
   'Mustard greens are washed, then withered in the sun or air-dried for a few hours until the leaves soften and lose some of their moisture. They are layered with salt — and often a little sugar and a spoonful of cooked rice or rice water to feed the fermentation — then packed tightly into a jar or clay crock and weighted so the greens stay under their own brine. The jar is left at room temperature for several days to a few weeks, until the greens turn sour, olive-green, and pleasantly crisp. Kept cool, spey jruk lasts for months; before eating it is rinsed, squeezed, and chopped to taste.',
   'Spey jruk is served as a sour side dish next to grilled meats, fish, and rich stews, cutting through the fat. It is stir-fried with pork, beef, or eggs, dropped into soups for a tangy lift, and eaten straight with rice and a dip of prahok or chili. Chopped, it goes into omelettes and fried rice, and it is a common accompaniment to rice porridge (borbor).',
   'Fermentation time is the main variable — a few days gives a mild, crunchy pickle, while several weeks makes it deeply sour and soft. Some families steer the sourness with garlic, chili, palm sugar, or a splash of rice water; others salt the greens heavily and leave the sugar out. The greens themselves change with the season and with the market, and some cooks press the pickle hard while others leave it loose in the jar. Each batch carries the taste of the kitchen that started it.',
   null,
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:52:00.000Z',
   'trey-chaar',
   'Trey Chaar',
   'ត្រីឆ្អើរ',
   'Smoked Fish',
   'Freshwater fish are salted, then hung over a slow, smoky fire until the flesh firms and the skin turns amber. Trey chaar is Cambodia''s smoked fish — deeply savory, lightly salty, and smoky enough to season a whole pot of rice.',
   array['smoky', 'savory', 'salty', 'firm']::text[],
   '/images/trey-chaar.jpg',
   'Rows of golden-brown smoked fish laid out on bamboo mats beside a bundle of smoked fish hung to dry.',
   'Freshwater fish — snakehead, catfish, and other river fish — are cleaned and gutted, sometimes split open and sometimes left whole, then rubbed inside and out with salt and left to sit for an hour or overnight. They are hung from bamboo rails or laid on a rack over a slow, smoldering fire of wood, coconut husk, or rice husk, kept low and smoky so the fish cures and dries rather than grills. After a few hours to a day the flesh firms up and the skin darkens to amber-brown. The fish is then rested, cooled, and stored hanging in a dry, airy place or in a jar, where the salt and smoke keep it for weeks.',
   'Trey chaar is usually grilled or fried to re-crisp the skin, then eaten with rice as a main or a side dish with fresh vegetables and a chili or prahok dip. It is flaked into fried rice, added to soups and curries for smoky depth, and crumbled into salads. Small smoked fish are pounded with chili, garlic, and lime into a smoky relish, and the fish is also eaten on its own as a snack.',
   'Families differ on how much salt goes into the rub and how long the fish rests before it meets the fire. The smoke itself changes with the fuel — coconut husk gives a sweet, dark smoke, rice husk a gentler one, and hardwood something sharper — so no two batches taste the same. Some cooks smoke lightly for a moist, tender fish, others hard and long for a dry one that keeps. The species is whatever the catch provides, and the size of the fish sets the timing.',
   null,
   'published'),
  ('57631f4a-b195-4522-93af-91e94f2eb3e2',
   '2025-09-01T11:51:00.000Z',
   'kwa-ko',
   'Kwa Ko',
   'ខ្វាគោ',
   'Fermented Beef Sausage',
   'Beef is minced with garlic, salt, sugar, and rice, packed into casings, then fermented and dried until the links firm up and turn deep red. Sour, savory, and faintly smoky, kwa ko turns one animal into provisions that hold for weeks.',
   array['savory', 'slightly sour', 'aromatic', 'smoky']::text[],
   '/images/kwa-ko.jpg',
   'Links of dark red, cured kwa ko sausage coiled in a woven bamboo basket.',
   'Beef is minced or pounded, then mixed with salt, sugar, garlic, and often cooked rice or a little rice powder, which feeds the fermentation and helps the sausage set. Some families season the mixture further with black pepper, chili, or galangal. The mixture is packed into natural casings and tied into short links, then left to ferment at room temperature for a day or two. The links are afterwards hung or laid out to dry and firm up — sometimes in the sun, sometimes over a light smoke — until they turn deep red and dense. Stored cool or in a jar they keep for weeks, and before eating they are grilled, fried, or steamed and sliced.',
   'Kwa ko is grilled or pan-fried and sliced into rounds, eaten with rice as a main or a side dish. It is a popular snack with beer and a common picnic and travel food, because it keeps without refrigeration. Sliced, it goes into fried rice, stir-fries, and noodle dishes, and it is usually set out with fresh vegetables, herbs, and a chili-lime or prahok dip.',
   'Seasoning is where households diverge: some keep kwa ko simply salty and garlicky, others push the sugar for a sweeter, stickier link or add pepper, chili, and galangal for heat and aroma. How long the mixture ferments before drying decides the sourness, and how finely the beef is minced and how long it dries decides the texture — soft and juicy links or hard and chewy ones. Some cooks smoke the links lightly, others dry them in the sun, and the fat-to-lean ratio of the beef moves the finished sausage from dry and firm to rich and tender.',
   null,
   'published');

